### ISSUE TITLE
Demographic Analysis

### ISSUE THREAD

**Issue by leggitta** [Data4Democracy/VA-open-data#22]
Following @synflyn28's [initial demographic exploration](https://github.com/Data4Democracy/VA-open-data/blob/master/ipynb/reid_demographics.ipynb), I have some additional follow up questions ...

- [ ] Compare veteran metrics to general population (by state)
- [ ] Map regional variation in demographics (by state)
- [ ] Identify outliers (see box plots)
- [ ] Look for significant correlations

Feel free to add additional questions in the comments

**Comment by WillGiang** [comment]
I brought up an issue with the boxplots in [Slack ](https://datafordemocracy.slack.com/archives/C82GX6ULR/p1516333181000370)

With regards to the outliers for Disability, they're from Washington DC and Puerto Rico.
The outlier for Poverty is Puerto Rico.

**Comment by bbrewington** [comment]
I'm going to grab some ACS data that could be used to re-create the state maps shown in the image below

I'll be using the R package acs to pull the data, and will collect it into a CSV file and upload it to the data.world workspace - https://data.world/leggitta/va-open-data

https://www.census.gov/library/visualizations/2015/comm/our-nation-s-veterans.html

![](https://www.census.gov/content/dam/Census/library/visualizations/2015/comm/ACS13VeteransPoster.png)
[Source: US Census Bureau]
